In [1]:
import os
# Change directory to use_case (parent directory)
os.chdir('C:/Users/as_cu/Desktop/use_case')

In [2]:
from scripts.data_loader import DataLoader
from scripts.data_cleaner import DataCleaner
from scripts.visualizer import Visualizer
from scripts.formatter import Formatter
from scripts.statistical_analyzer import StatisticalAnalyzer
import pandas as pd

In [3]:
# Load A/B test data
data_loader = DataLoader()
ab_test_data = data_loader.load("ab_test_br.csv")
ab_test_data.head()

Data loaded successfully. Shape: (124457, 6)

,keychain_udid,event_date,ab_test_cohort,ads_revenue,meaningful_reactions,sessions
0,secure_4A740435-89B3-4954-91F6-9B0415E25A52,09/11/2023,control,0.009652,3,12
1,secure_3FCDD36C-9708-4CC7-8DF0-B35EE8BA90F0,09/11/2023,test,0.033341,0,19
2,secure_6F665CEC-B52C-4404-9870-17A7EDFF5F7A,09/11/2023,test,0.082532,6,144
3,secure_72BFD723-8DDF-42D8-87E5-820FF0FE499A,09/11/2023,control,0.002670,5,26
4,secure_29E40A03-5C8F-4145-92AD-68E81426EEA1,10/11/2023,test,0.013517,3,53

In [4]:
# Clean A/B test data
data_cleaner = DataCleaner(ab_test_dataset=ab_test_data)
data_cleaner.remove_rows_with_missing_user_id(user_id_column='keychain_udid')
ab_test_data = data_cleaner.dfab
ab_test_data.head()

-- Removing rows with missing keychain_udid
Number of null values in keychain_udid: 13
Dropped 13 rows with missing keychain_udid

,keychain_udid,event_date,ab_test_cohort,ads_revenue,meaningful_reactions,sessions
0,secure_4A740435-89B3-4954-91F6-9B0415E25A52,09/11/2023,control,0.009652,3,12
1,secure_3FCDD36C-9708-4CC7-8DF0-B35EE8BA90F0,09/11/2023,test,0.033341,0,19
2,secure_6F665CEC-B52C-4404-9870-17A7EDFF5F7A,09/11/2023,test,0.082532,6,144
3,secure_72BFD723-8DDF-42D8-87E5-820FF0FE499A,09/11/2023,control,0.002670,5,26
4,secure_29E40A03-5C8F-4145-92AD-68E81426EEA1,10/11/2023,test,0.013517,3,53

In [5]:
# Display distributions of the three variables
visualizer = Visualizer(ab_test_data)
distribution_figs = visualizer.display_distributions(['ads_revenue', 'meaningful_reactions', 'sessions'])

In [6]:
# Time series graphs by group (test/control)
time_series_figs = visualizer.time_series_by_group(['ads_revenue', 'meaningful_reactions', 'sessions'])

In [ ]:
# Create table with means, p-values and significance by group (test/control)
formatter = Formatter(ab_test_data)
# Outlier removed data for statistical analysis
summary_table = formatter.abtest_summary_table(['ads_revenue', 'meaningful_reactions', 'sessions'])
summary_table

,Variable,N Test,N Control,Average Test,Average Control,T-Test Result,Permutation Test Result
0,ads_revenue,61937,61262,0.013,0.014,"p-value: 0.001, is_significant","p-value: 0.001, is_significant"
1,meaningful_reactions,61994,61390,0.741,0.692,"p-value: 0.0, is_significant","p-value: 0.001, is_significant"
2,sessions,61873,61337,26.730,26.526,"p-value: 0.363, is_not_significant","p-value: 0.339, is_not_significant"

In [8]:
# Export all graphs to PDF
all_figs = distribution_figs + time_series_figs
formatter.export_to_pdf(all_figs, filename='ab_test_analysis.pdf')

Image contains an alpha channel. Computing a separate soft mask (/SMask) image to store transparency in PDF.
Image contains an alpha channel. Computing a separate soft mask (/SMask) image to store transparency in PDF.
Image contains an alpha channel. Computing a separate soft mask (/SMask) image to store transparency in PDF.
Image contains an alpha channel. Computing a separate soft mask (/SMask) image to store transparency in PDF.
Image contains an alpha channel. Computing a separate soft mask (/SMask) image to store transparency in PDF.
Image contains an alpha channel. Computing a separate soft mask (/SMask) image to store transparency in PDF.

PDF exported to: C:/Users/as_cu/Desktop/use_case/output\ab_test_analysis.pdf